### ISSUE TITLE
Аудиозаписи

### ISSUE THREAD

**Issue by foshechka** [fdcore/vk.api#9]
Сделай, пожалуйста, поиск по аудиозаписям с поноценным плеером, как в ВК и возможностью скачивать треки. Было хорошо, если бы еще была возможжность загружать треки в ВК.

**Comment by fdcore** [comment]
Это только библиотека, всё в ваших руках.

Поиск: [https://vk.com/dev/audio.search](https://vk.com/dev/audio.search)
